CREATE DATABASE auth_DB;
USE auth_DB;

CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT,
full_name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
mobile VARCHAR(15) NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(20),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
